ansible_user: ec2-user
ansible_password: DevOps321
MONGODB_HOST: mongodb-{{env}}.daws88.sbs
CATALOGUE_HOST: catalogue-{{env}}.daws88.sbs
REDIS_HOST: redis-{{env}}.daws88.sbs
USER_HOST: user-{{env}}.daws88.sbs
CART_HOST: cart-{{env}}.daws88.sbs
MYSQL_HOST: mysql-{{env}}.daws88.sbs
SHIPPING_HOST: shipping-{{env}}.daws88.sbs
PAYMENT_HOST: payment-{{env}}.daws88.sbs
RABBITMQ_HOST: rabbitmq-{{env}}.daws88.sbs
FRONTEND_HOST: frontend-{{env}}.daws88.sbs
app_version: v3